### ISSUE TITLE
Humblebundle not working

### ISSUE THREAD

**Issue by n00b42** [dregimbal/UserScripts#1]
Issue: I tried to use your script for the first time today but I think it is currently not working for Humble Bundle.
Reason: It seems Humblebundle does not include Steam links anymore.

**Comment by n00b42** [comment]
Hint: Using another script to add the steam is a workaround, e.g.
https://greasyfork.org/en/scripts/27373-humble-bundle-steam-links-adder

**Comment by dregimbal** [comment]
Whoops, I hadn't noticed because I've been using that script and had been relying on it unknowingly.
Should be fixed now

**Comment by dregimbal** [comment]
Fixed in: https://github.com/dregimbal/UserScripts/commit/59286916b0686a4f723da2315958a410d87828dd
